# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=8)),
                ('token', models.CharField(max_length=80)),
            ],
        ),
    ]
