from flask import render_template, request, jsonify
from app import app
from .forms import (
    BigDataStoreForm
)

from functools import wraps

def check_auth(username, password):
    return username == 'dummy' and password == 'dummy'

def authenticate():
    message = {'error': "Authentication Failure"}
    resp = jsonify(message)

    resp.status_code = 401
    resp.headers['WWW-Authenticate'] = 'Basic realm="Example"'

    return resp

def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth:
            return authenticate()

        elif not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated


BigData = [
    {"data": "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife."},
    {"data": "To be fond of dancing was a certain step towards falling in love."},
    {"data": "Jane Austen was an English novelist known primarily for her six major novels which interpret, critique and comment upon the life of the British landed gentry at the end of the 18th century"},
    {"data": "travelling, skiing, swimming, hockey, cricket are sports"},
    {"data": "target.com is an online competitor"},
    {"data": "Amazon supports online selling and buying for retail business by hosting an online platform on a cloud."},
    {"data": "Google is a search based company, they crawl all the pages on internet at specified frequencies and use pagerank alogorithm to rank the pages."},
    {"data": "5/31/2016 - Special Operations Forces Invade Tampa…In A Training Exercise - DailyCaller, WFLA, Daily Mail and RT"},
    {"data": "5/27/2016 - How to commemorate Memorial Day - USMemorialDay.org"},
    {"data": "5/26/2016 - Obama administration targets spying threat on campus - Reuters"},
    {"data": "5/25/2016 - Google lobbyists’ White House visits - CNBC"},
    {"data": "5/24/2016 - Portland school board bans climate change-denying materials - Portland Tribune"},
    {"data": "5/23/2016 - Israel’s risk-based approach to airport security - London's Daily Telegraph"},
    {"data": "5/20/2016 - Hackers target presidential candidates, U.S. spy chief says - Reuters"},
    {"data": "5/19/2016 - Police see promise in high-tech ‘GPS bullets’ - UK Daily Mail"},
    {"data": "5/18/2016 - Medal of Valor awarded to 13 at White House - Associated Press"},
    {"data": "5/17/2016 - Senate Bill Calls for Women to Register for Draft in 2018 - NJ.com"},
    {"data": "5/16/2016 - U.S. Navy Poised to Take Ownership of its Largest Warship - Associated Press"},
    {"data": "5/13/2016 - U.S. activates Romanian missile defense site, angering Russia - Reuters"},
    {"data": "5/12/2016 - Prince Harry Brings Invictus Games to Florida - VOA"},
    {"data": "5/11/2016 - Push for $15 Raises Pay–and Tensions - The Wall Street Journal"},
    {"data": "5/10/2016 - Student off-campus speech and the First Amendment - Constitution Center at YahooNews"},
    {"data": "5/9/2016 - FDA unveils new regulations on e-cigarettes - CBS News"},
    {"data": "5/6/2016 - Yom HaShoah 2016: Remembering those killed during the Nazi Holocaust - UK Metro News"},
    {"data": "5/5/2016 - Facebook and the News - Gizmodo"},
    {"data": "5/4/2016 - U.S. families struggling with teens’ phone use - Reuters"},
    {"data": "5/3/2016 - ‘Reckless’ Russian fliers continue to taunt American jets - New York Post"},
    {"data": "5/2/2016 - Kansas governor withdraws from Syrian refugee program - Reuters"},
    {"data": "4/29/2016 - Three linked to San Bernardino terrorist charged with marriage fraud - Reuters"},
    {"data": "4/27/2016 - Federal judge upholds voter ID law in North Carolina - Reuters"},
    {"data": "4/26/2016 - Cruz and Kasich unite to take down Donald Trump - NY Post"},
    {"data": "4/25/2016 - Speed-Camera Debate Ramps Up - The Wall Street Journal"},
    {"data": "4/22/2016 - Fight Over Delegate Rules Escalates for Both Parties - The Wall Street Journal"},
    {"data": "4/21/2016 - Obama meets Saudi king with Iran on agenda - Reuters"},
    {"data": "4/20/2016 - Thirty years on, Chernobyl remembered by Philadelphia-area Ukrainians - Philly.com"},
    {"data": "4/19/2016 - Construction Unions’ Grip on NYC Begins to Show Cracks - The Wall Street Journal"},
    {"data": "4/18/2016 - Iran Ignores Visa Applications from U.S. Congressmen - The Washington Free Beacon"},
    {"data": "4/15/2016 - Russian jets make ‘simulated attack’ passes near U.S. destroyer - Reuters"},
    {"data": "4/14/2016 - Gambling only a short-term fix for cash-starved states: study - Reuters"},
    {"data": "4/11/2016 - VA bosses in 7 states falsified vets’ wait times for care - Reuters and USA Today"},
    {"data": "4/8/2016 - White House declines to support encryption legislation - Reuters"},
    {"data": "4/7/2016 - McCain: War against ISIS turning into Vietnam - The Hill"},
    {"data": "4/6/2016 - US military gives go ahead to ‘Gremlin’ drones - UK Daily Mail"},
    {"data": "4/5/2016 - Panama Papers explained - New York Daily News"},
    {"data": "4/4/2016 - CA parents planned one-day boycott over school year start date - Orange County Register"},
    {"data": "4/1/2016 - Pentagon wages cyberwar against Islamic State - Los Angeles Times"},
    {"data": "3/31/2016 - Some superdelegates vow to back Clinton even if Sanders wins NY primary - NY Daily News"},
    {"data": "3/30/2016 - Marines forming new cyberwarrior unit - Stars and Stripes"},
    {"data": "3/29/2016 - Brave British travelers treated at Belgian hospital for ‘severe battlefield’ wounds - London's Daily Telegraph"},
    {"data": "3/25/2016 - Police officer: protesters were ‘the most hateful…people I’ve ever seen’ - The Washington Post"},
    {"data": "3/24/2016 - Report: Israeli company helping FBI crack iPhone security - Israel's YNet News"},
    {"data": "3/23/2016 - Supreme Court rejects suit against Colorado over marijuana law - Reuters and Los Angeles Times"},
    {"data": "3/22/2016 - Cuba arrests dozens of human rights protesters before Obama’s arrival - USA Today"},
    {"data": "3/21/2016 - Justice Department Policing Tactic Guarded as ‘Classified’? - The Wall Street Journal"},
    {"data": "3/18/2016 - Outmoded U.S. immigration system poses security risk: study - Reuters"},
    {"data": "3/17/2016 - ISIS Documents Identify Thousands Of Jihadis - Britain's Sky News"},
    {"data": "3/16/2016 - 5 years later, Japan still struggles to recover from tsunami disaster - USA Today"},
    {"data": "3/15/2016 - Vermont legislature on track to be first in U.S. to legalize marijuana - Reuters"},
    {"data": "3/14/2016 - Carson becomes second candidate to back Trump - London's Daily Telegraph"},
    {"data": "3/11/2016 - Three-time champion Seavey in lead halfway through Alaska’s Iditarod - Reuters"},
    {"data": "3/10/2016 - Biden criticizes Palestinians for not condemning attack - The Washington Post"},
    {"data": "3/9/2016 - Ray Tomlinson, creator of email, dies - KDVR.com"},
    {"data": "3/8/2016 - Former first lady Nancy Reagan dies at 94 - Reuters"},
    {"data": "3/7/2016 - After a year in space, Scott Kelly returns 2 inches taller - USA Today"},
    {"data": "3/4/2016 - DoD ‘Hack the Pentagon’ competition - Fox News/AP"},
    {"data": "3/3/2016 - See That Billboard? It May See You, Too - The New York Times"},
    {"data": "3/2/2016 - Massive IRS data breach much bigger than first thought - CBS News"},
    {"data": "3/1/2016 - Voter turnout varies drastically between parties - CBS News"},
    {"data": "2/29/2016 - U.S. test-fires ICBMs to stress its power to Russia, North Korea - Reuters"},
    {"data": "2/26/2016 - Archaeologists dig up fabrics dating back to Kings David and Solomon - Haaretz"},
    {"data": "2/25/2016 - Largest ever US-South Korea military drill planned as a ‘warning to Pyongyang’ - London's Daily Telegraph"},
    {"data": "2/24/2016 - U.S., Russia Agree on Cease-Fire for Syria - The New York Post"},
    {"data": "2/23/2016 - Russia wants to fly hi-tech spy planes over U.S. - CBS News"},
    {"data": "2/22/2016 - NJ Cuban-Americans Speak Out Against Obama Visit - PolitickerNJ.com"},
    {"data": "2/19/2016 - Hospital explains decision to pay ransom to hackers - CBS News"},
    {"data": "2/18/2016 - Apple refuses to unlock phone of San Bernardino terrorist - WREG News 3 Memphis"},
    {"data": "2/17/2016 - Supreme Court Memorializes Justice Antonin Scalia - The Washington Post and The Wall Street Journal"},
    {"data": "2/16/2016 - Without Antonin Scalia, what’s next for the Supreme Court? - CBS News"},
    {"data": "2/12/2016 - Presidents Day 2016"},
    {"data": "2/11/2016 - Moscow warns US over missile system deployment to S. Korea - Agence France-Presse"},
    {"data": "2/10/2016 - Thousands of voters confused by ‘independent’ party name - Boston Globe"},
    {"data": "2/9/2016 - Russian firepower helps Syrian forces edge toward Turkey border - Reuters"},
    {"data": "2/8/2016 - Killing the Working Class at Wal-Mart - The Wall Street Journal"},
    {"data": "2/5/2016 - Hillary Clinton, Bernie Sanders battle over meaning of ‘progressive’ - USA Today"},
    {"data": "2/4/2016 - FBI joins probe of Flint, Michigan’s lead contaminated water - Reuters"},
    {"data": "2/3/2016 - U.S. Warship Sails Near Island Claimed by China - The Wall Street Journal"},
    {"data": "2/2/2016 - Driverless cars work great in sunny California. But how about in a blizzard? - The Washington Post"},
    {"data": "2/1/2016 - Walmart closures a “double blow” for many frustrated residents - CBS News"},
    {"data": "1/29/2016 - United States eases trade restrictions with Cuba - BBC News"},
    {"data": "1/28/2016 - Wounded Warrior Project accused of wasting donation money - CBS News"},
    {"data": "1/27/2016 - Air Force Reminds Commanders: Conceal-Carry, Open-Carry OK on Base - Military.com"},
    {"data": "1/26/2016 - Last-Minute Democratic Town Hall With Clinton, Sanders and O’Malley - The Wrap at YahooNews and The Street"},
    {"data": "1/25/2016 - U.S. Tightens Visa-Waiver Rules Following Terror Attacks - The Wall Street Journal"},
    {"data": "1/22/2016 - Kerry: Some Iran sanctions relief likely to go to terrorists - AP at Times of Israel"},
    {"data": "1/21/2016 - Iraq’s Oldest Christian Monastery Destroyed by Islamic State - Associated Press"},
    {"data": "1/20/2016 - Supreme Court will review Obama’s immigration executive actions - CBS News"},
    {"data": "1/19/2016 - Students upset with Wisconsin’s ban on game chants - NBC's KARE11 Minneapolis/St. Paul"},
    {"data": "1/18/2016 - Martin Luther King Jr. Day 2016"},
    {"data": "1/15/2016 - Ringling Bros. ending elephant acts - AP at The New York Post"},
    {"data": "1/14/2016 - 2016 State of the State addresses"},
    {"data": "1/13/2016 - U.S. Border Agents To Inspect U.S.-Bound Trucks On Mexican Soil - CBS Dallas Fort Worth"},
    {"data": "1/12/2016 - In final State of Union, Obama aims to define his presidency - Associated Press"},
    {"data": "1/11/2016 - The story behind the tent on Alabama’s football sideline - USA Today"},
    {"data": "12/18/2015 - Merry Christmas – back on Jan. 11"},
    {"data": "12/17/2015 - Congress Poised to Lift Oil Export Ban - The Texas Tribune"},
    {"data": "12/16/2015 - Secret Policy Blocks Agents From Looking at Social Media of Visa Applicants - ABC News"},
    {"data": "12/15/2015 - U.S. Army changing dog tags for first time in 40 years - CNN and Army Times"},
    {"data": "12/14/2015 - GOP preparing for contested convention - The Washington Post"},
    {"data": "12/11/2015 - Hero soldier who lost all his limbs finds purpose inspiring other amputees - New York Post"},
    {"data": "12/10/2015 - Study: chemicals in e-cigs linked to lung disease - KFOR.com"},
    {"data": "12/9/2015 - Trump: Ban all Muslim travel to the U.S. - Reuters"},
    {"data": "12/8/2015 - Largest destroyer built for Navy headed to sea for testing - The Boston Herald"},
    {"data": "12/7/2015 - Google accused of spying on students in FTC privacy complaint - The Wall Street Journal"},
    {"data": "12/4/2015 - American WWII vet becomes first soldier honored for saving Jews - CBS News"},
    {"data": "12/3/2015 - Joint Chiefs chairman: ‘We have not contained’ ISIS - The Hill"},
    {"data": "12/2/2015 - Obama Ignores ‘Wrap-It-Up’ Beeps, Talks and Talks at Climate Summit - NBC News"},
    {"data": "12/1/2015 - Ben Carson meets with Syrians at refugee camps in Jordan - YahooNews"},
    {"data": "11/30/2015 - Casinos Seek Labor Law Exemption - The Wall Street Journal"},
    {"data": "11/23/2015 - Thanksgiving 2015"},
    {"data": "11/20/2015 - Rising Rates Pose Challenge to Health Law - The Wall Street Journal"},
    {"data": "11/19/2015 - Paris Attacks Fuel Debate Over Spying - The Wall Street Journal"},
    {"data": "11/18/2015 - Republicans to Obama: Keep Syrian refugees out - CNN"},
    {"data": "11/17/2015 - CIA chief warns Islamic State may have other attacks ready - Reuters"},
    {"data": "11/16/2015 - Army captain who tackled suicide bomber gets Medal of Honor - New York Post"},
    {"data": "11/13/2015 - Calorie counts on menus aren’t working, new research shows - Politico New York"},
    {"data": "11/12/2015 - Obama’s executive action on immigration blocked - Associated Press"},
    {"data": "11/11/2015 - Veterans Day 2015"},
    {"data": "11/10/2015 - Obama kills the Keystone Pipeline - Reuters"},
    {"data": "11/9/2015 - Bernie Sanders Takes Gloves Off Against Hillary Clinton - The Wall Street Journal"},
    {"data": "11/6/2015 - TX Governor Abbott issues warning over immigrant detentions - Reuters and IB Times"},
    {"data": "11/5/2015 - Weapons smuggled past TSA screeners with ease: officials - New York Post"},
    {"data": "11/4/2015 - Republican Campaigns Take Greater Control Over Debate Formats - NPR"},
    {"data": "11/3/2015 - Voters Weigh Taxes, Wages and Legalizing Pot - The Wall Street Journal"},
    {"data": "11/2/2015 - U.S. to deploy special forces to Syria in about-face for Obama - London's Daily Telegraph"},
    {"data": "10/30/2015 - Walmart seeks to test drones for home delivery, pickup - Reuters"},
    {"data": "10/29/2015 - Why NYC is banning synthetic marijuana - CBS News"},
    {"data": "10/28/2015 - Angry China shadows U.S. warship near man-made islands - Reuters"},
    {"data": "10/27/2015 - Russian subs near undersea cables concerns U.S. - London's Daily Mirror and The NY Times"},
    {"data": "10/26/2015 - 24 states sue Obama over coal plant emissions rule - The Hill"},
    {"data": "10/23/2015 - Marijuana use, disorders doubled since 2001 - Reuters"},
    {"data": "10/22/2015 - HS students arrested for hacking into school computer system - NY's WPIX11 TV"},
    {"data": "10/21/2015 - Carson, Trump request Secret Service protection - AP and CNN"},
    {"data": "10/20/2015 - Drone Close Calls Spur Government to Require Registration - ABC News"},
    {"data": "10/19/2015 - McDonald’s franchisees say all-day breakfast is a nightmare - Business Insider"},
    {"data": "10/16/2015 - POWs visit Japan for 70th anniversary of the end of World War II - Daily Mail and AP"},
    {"data": "10/15/2015 - Supreme Court tells lawyers: Stand in line yourselves. - The Washington Post"},
    {"data": "10/14/2015 - 8th grader suspended for wearing patriotic T-shirt - KATU News"},
    {"data": "10/13/2015 - Podium on standby for Biden in first Democratic presidential debate - London's Daily Mail"},
    {"data": "10/12/2015 - Columbus Day 2015"},
    {"data": "10/9/2015 - U.S. Rules Out Cooperation With Russia - The Wall Street Journal"},
    {"data": "10/8/2015 - Justice Department set to free 6,000 prisoners - The Washington Post"},
    {"data": "10/7/2015 - Twelve Countries Reach Trans-Pacific Partnership Deal - VOA News"},
    {"data": "10/6/2015 - Historic rainfall pounds South Carolina - CBS News"},
    {"data": "10/5/2015 - Remains of WWII Marine returned home - KnoxNews.com"},
    {"data": "10/2/2015 - Russian Airstrike in Syria Targeted CIA-Backed Rebels, not ISIS - The Wall Street Journal"},
    {"data": "10/1/2015 - Pope secretly met Kentucky clerk over gay marriage licenses - CBS News"},
    {"data": "9/30/2015 - Obama, Putin spar over Syria - Reuters"},
    {"data": "9/29/2015 - Hackers stole 5.6 million US fingerprints – more than estimated - CNN Money"},
    {"data": "9/28/2015 - Obama Arrives In NYC For UN General Assembly - CBS New York"},
    {"data": "9/25/2015 - Pope delivers political message on immigration, tolerance to Congress - CNN"},
    {"data": "9/24/2015 - 6 key issues awaiting Xi and Obama in Washington - CBS News"},
    {"data": "9/23/2015 - Ex-Peanut Executive Sentenced to 28 Years in Prison for Salmonella Coverup - The Wall Street Journal"},
    {"data": "9/22/2015 - U.S. to Boost Refugee Intake by 30,000 Over Two Years - The Wall Street Journal"},
    {"data": "9/21/2015 - New prosthetic arm can restore lost sense of touch - CNET"},
    {"data": "9/18/2015 - 50 Spies Say ISIS Intelligence Was Cooked - The Daily Beast"},
    {"data": "9/17/2015 - Price Tag of Bernie Sanders’s Proposals - The Wall Street Journal"},
    {"data": "9/16/2015 - Ben Carson ‘not worried’ by Trump - London's Daily Telegraph"},
    {"data": "9/14/2015 - All-male infantry units outperform teams with women - USA Today"},
    {"data": "9/11/2015 - Commemorating 9/11"},
    {"data": "9/10/2015 - Hillary Clinton on Private Email: ‘That Was a Mistake. I’m Sorry’ - ABC News"},
    {"data": "9/9/2015 - Obama orders government contractors to offer paid sick leave - Reuters"},
    {"data": "9/8/2015 - U.S. heroes to be honored this week - Reuters"},
    {"data": "5/29/2015 - 35 years after Mount St. Helens eruption, nature returns - CBS News"},
    {"data": "5/28/2015 - Criminals gain access to taxpayers’ personal information - Fortune"},
    {"data": "5/27/2015 - Obama Rethinks Strategy on ISIS - The Wall Street Journal"},
    {"data": "5/26/2015 - Senate blocks measures to extend NSA program - CNN"},
    {"data": "5/22/2015 - Memorial Day 2015 - USMemorialDay .org"},
    {"data": "5/21/2015 - Obama Calls for Restricting Military Gear to Local Police - The Wall Street Journal"},
    {"data": "5/20/2015 - Texas Prohibits Local Fracking Bans - The Wall Street Journal"},
    {"data": "5/19/2015 - Harvard Accused of Bias Against Asian-Americans - The Wall Street Journal"},
    {"data": "5/18/2015 - Secret Service Arrests Man After Drone Flies Near White House - The New York Times"},
    {"data": "5/15/2015 - SC teen banned from flying flag on truck sparks protests, change - New York Daily News"},
    {"data": "5/14/2015 - Iran warns US against stopping Yemen-bound aid ship - Agence France-Presse"},
    {"data": "5/13/2015 - U.S. denies snub by Persian Gulf leaders skipping Obama’s summit - Los Angeles Times"},
    {"data": "5/12/2015 - NFL was paid to honor National Guard? - NJ.com"},
    {"data": "5/11/2015 - How a college term paper led to a constitutional amendment - Yahoo News"},
    {"data": "5/8/2015 - NSA phone surveillance not authorized - Reuters"},
    {"data": "5/7/2015 - California bill to end ‘beliefs’ exemption for vaccines - Reuters"},
    {"data": "5/6/2015 - Clinton, Democratic opponents to debate 6 times - CNN and NY Daily News"},
    {"data": "5/5/2015 - Supreme Court prods Obama administration in marijuana dispute - Christian Science Monitor"},
    {"data": "5/4/2015 - U.S. Navy Starts to Accompany Ships in Strait Where Iran Seized Cargo Carrier - The Wall Street Journal"},
    {"data": "5/1/2015 - The history-making, chaotic evacuation of Saigon 40 years later - CNN"},
    {"data": "4/30/2015 - Baltimore’s businesses fear investment, tourism will be hit - Reuters"},
    {"data": "4/28/2015 - Wal-Mart suddenly closed 5 stores and laid off thousands of workers - Business Insider"},
    {"data": "4/27/2015 - Franchisees upset over McDonald’s wage increase - Business Insider"},
    {"data": "4/24/2015 - Judge OKs 65-year deal over NFL concussions - The Washington Post"},
    {"data": "4/23/2015 - Supreme Court Curbs Drug-Sniffing Dogs During Traffic Stops - The Wall Street Journal"},
    {"data": "4/22/2015 - Disaster Plans for Oil Trains - The Wall Street Journal"},
    {"data": "4/21/2015 - E-Cigarette Use Rises Among U.S. Teens as Cigarette Use Falls - The Wall Street Journal"},
    {"data": "4/20/2015 - Synthetic Marijuana Causes Rash of Hospitalizations - CNN and Forbes"},
    {"data": "4/17/2015 - Jackie Robinson honored throughout MLB and beyond - CBS News"},
    {"data": "4/16/2015 - Spring Break madness cure - Yahoo News"},
    {"data": "4/15/2015 - How the Post covered Lincoln’s assassination in 1865 - New York Post"},
    {"data": "4/14/2015 - U.S. Widens Role in Saudi-led Campaign - The Wall Street Journal"},
    {"data": "4/13/2015 - VA makes little headway in effort to cut waits for care - Associated Press"},
    {"data": "4/10/2015 - Kansas will allow concealed carry of guns without a permit - Reuters"},
    {"data": "4/9/2015 - Tsarnaev guilty of all 30 counts in Boston bombing - Boston Globe"},
    {"data": "4/8/2015 - Army’s new tattoo policy - Army Times"},
    {"data": "4/7/2015 - Republicans push demand for a vote on Iran nuclear deal - Reuters"},
    {"data": "4/6/2015 - Iranian nuclear agreement - New York Post"},
    {"data": "4/3/2015 - California governor: statewide water restrictions - CBS News"},
    {"data": "4/2/2015 - Chinese flock to USA to give birth to U.S. citizens - USA Today"},
    {"data": "4/1/2015 - State Department: Clinton sent only 4 emails about drones - Associated Press"},
    {"data": "3/31/2015 - Astronauts board space station for 1-year mission - Associated Press"},
    {"data": "3/30/2015 - Supreme Court hears Confederate license plates case - USA Today"},
    {"data": "3/23/2015 - Spring Break"},
    {"data": "3/20/2015 - Secret Service wants to build $8M fake White House for training - New York Post"},
    {"data": "3/19/2015 - LAPD uses its helicopters to stop crimes before they start - Los Angeles Times"},
    {"data": "3/18/2015 - NFL star Chris Borland retiring at 24 - CBS News"},
    {"data": "3/17/2015 - It’s been 30 years since the first .com - CBS News"},
    {"data": "3/16/2015 - Study Supports Raising Tobacco-Buying Age - The Wall Street Journal"},
    {"data": "3/13/2015 - Federal Agents Raid Suspected Fake Schools - The Wall Street Journal"},
    {"data": "3/12/2015 - Utah lawmakers pass bill allowing for execution by firing squad - Los Angeles Times"},
    {"data": "3/11/2015 - Republicans send open letter to Iran - Associated Press"},
    {"data": "3/10/2015 - U.S. contractor who critized employer faces jail & fines in UAE - The Associated Press"},
    {"data": "3/9/2015 - Wisconsin Lawmakers Pass Right-to-Work Bill - The Associated Press"},
    {"data": "3/6/2015 - Food fight brewing in Washington over school lunch standards - McClatchy News"},
    {"data": "3/5/2015 - Hillary Clinton Used Personal Email Account at State Dept. - The New York Times"},
    {"data": "3/4/2015 - Israel’s Netanyahu Urges Congress to Block ‘Bad Deal’ With Iran - The Wall Street Journal"},
    {"data": "3/3/2015 - Hockey legend’s recovery highlights adult stem-cell advances - The Toledo Blade"},
    {"data": "3/2/2015 - The inside story of the famous Iwo Jima photo - CNN"},
    {"data": "2/27/2015 - Vandals cut off internet service across northern Arizona - CBS News"},
    {"data": "2/26/2015 - Crackdown on drones goes local - USA Today"},
    {"data": "2/25/2015 - U.S., Iran Explore Option of 10-Year Nuclear Freeze - The Wall Street Journal"},
    {"data": "2/24/2015 - “Miracle on Ice” team celebrates 35 years later - CBS News"},
    {"data": "2/23/2015 - Amid controversy, oil trains quietly rerouted through Virginia towns - Reuters"},
    {"data": "2/20/2015 - Obama administration to allow allied countries to buy military drones - Los Angeles Times"},
    {"data": "2/19/2015 - US Officials Admit Concern Over Syrian Refugee Effort - ABC News"},
    {"data": "2/18/2015 - Federal Judge Blocks Obama’s Amnesty - The Daily Caller"},
    {"data": "2/17/2015 - Super strong cannabis responsible for quarter of new psychosis cases - London's Daily Telegraph"},
    {"data": "2/16/2015 - Presidents Day 2015"},
    {"data": "2/13/2015 - Marines Surrender Weapons Before Yemen Evacuation - Military .com"},
    {"data": "2/12/2015 - Obama asks Congress to approve war against ISIS militants - The Hill"},
    {"data": "2/11/2015 - Pittsburgh-area mall to implement Youth Escort Policy - Pittsburgh Post-Gazette"},
    {"data": "2/10/2015 - Japan hosts cyber security comptetition SECCON - Agence France-Presse"},
    {"data": "2/9/2015 - Brian Williams, trusted face of US television news, in trouble over made up war stories - London's Daily Telegraph"},
    {"data": "2/6/2015 - Americans OK with police drones – private ownership, not so much: Poll - Reuters"},
    {"data": "2/5/2015 - Average Mohamed counters terror message with cartoon videos - Associated Press"},
    {"data": "2/4/2015 - Armed with U.S. weapons, infamous militia beating ISIS - CBS News"},
    {"data": "2/3/2015 - Fierce fighting rages for key Ukraine town - Agence France-Presse"},
    {"data": "2/2/2015 - Swedish office puts chips under staff’s skin - BBC News"},
    {"data": "1/30/2015 - U.S. Spies on Millions of Drivers - The Wall Street Journal"},
    {"data": "1/29/2015 - Obama Meets New Saudi King - The Wall Street Journal"},
    {"data": "1/28/2015 - Auschwitz survivors gather for memorial 70 years after liberation - The Guardian"},
    {"data": "1/27/2015 - 2015 State of the State addresses"},
    {"data": "1/26/2015 - Supreme Court rules in favor of fired air marshal seeking whistleblower protection - Associated Press"},
    {"data": "1/23/2015 - Modi to welcome Obama in Fortress Delhi - Reuters"},
    {"data": "1/22/2015 - Boehner invites Benjamin Netanyahu to address Congress - CBS News"},
    {"data": "1/21/2015 - U.S. Supreme Court rules for Muslim inmate over prison beard ban - Reuters"},
    {"data": "1/20/2015 - State of the Union 2015 - ABC News"},
    {"data": "1/19/2015 - Martin Luther King Jr. Day 2015"},
    {"data": "1/16/2015 - U.S. Loosens embargo on Cuba - AP at FoxNews"},
    {"data": "1/15/2015 - Cracking Down on Skipping Class - The Wall Street Journal"},
    {"data": "1/14/2015 - Cuban dissidents out of prison but not entirely free - Rueters"},
    {"data": "1/13/2015 - White House to hold global security summit Feb 18: U.S. official - Reuters"},
    {"data": "1/12/2015 - French, foreign leaders walk arm-in-arm as millions protest Paris attacks - Reuters"},
    {"data": "12/19/2014 - Merry Christmas – Back on Jan. 12"},
    {"data": "12/18/2014 - Navy testing ‘spy fish’ based on bluefin tuna - The Christian Science Monitor"},
    {"data": "12/17/2014 - Buy a bond, get a green card - Philly.com"},
    {"data": "12/16/2014 - A penny costs almost twice its value to make - The Wall Street Journal"},
    {"data": "12/15/2014 - Google aquires spill preventing “smart spoon” - CBS News"},
    {"data": "12/12/2014 - See the Navy’s New Futuristic Laser Weapon in Action - ABC News"},
    {"data": "12/11/2014 - Ex-CIA Directors: Interrogations Saved Lives - The Wall Street Journal"},
    {"data": "12/10/2014 - U.S., NATO officially end Afghan combat mission - CBS News"},
    {"data": "12/9/2014 - House Intelligence Chief Says Torture Report Will Spur Attacks - ABC News"},
    {"data": "12/8/2014 - Orion passes test flight with flying colors - The Christian Science Monitor"},
    {"data": "12/5/2014 - NYC Mayor’s Wi-Fi Plan Draws Critics - The Wall Street Journal"},
    {"data": "12/4/2014 - 4 Pearl Harbor survivors gather for reunion - San Francisco Chronicle"},
    {"data": "12/3/2014 - Colo. regulators can’t answer basic pot questions - USA Today"},
    {"data": "12/2/2014 - FDA enforces nationwide calorie labeling - Yahoo News"},
    {"data": "12/1/2014 - Pakistani boot camps want to ‘re-program’ ISIS terrorists - New York Post"},
    {"data": "11/24/2014 - Thanksgiving 2014"},
    {"data": "11/21/2014 - President Obama announces executive action on Immigration - CBS News DFW"},
    {"data": "11/20/2014 - Democrats defeat bill to build controversial oil pipeline from Canada to US - London's Daily Telegraph"},
    {"data": "11/19/2014 - Palestinian terrorists kill four in Jerusalem Synagogue attack; Israel to destroy killers’ homes - CBS News"},
    {"data": "11/18/2014 - China tests malaria drug on an entire African nation - CBS News"},
    {"data": "11/17/2014 - Americans’ Cellphones Targeted in Secret U.S. Spy Program - The Wall Street Jounal"},
    {"data": "11/14/2014 - Appeals court upholds same-sex marriage bans in 4 states - CBS News"},
    {"data": "11/13/2014 - Obamacare 2015: Higher costs, higher penalties - CBS News"},
    {"data": "11/12/2014 - San Francisco soda tax falls short; Berkeley’s passes - San Francisco Chronicle"},
    {"data": "11/11/2014 - Veterans Day 2014"},
    {"data": "11/7/2014 - Germany: 25th anniversary of the fall of the Berlin Wall - Reuters"},
    {"data": "11/6/2014 - Republicans gain largest majorities in decades in state capitols, plan push for more tax cuts - Associated Press"},
    {"data": "11/5/2014 - Can Old Faithful compete with Netflix? - CBS News"},
    {"data": "11/4/2014 - Whether or not you vote is public record - New York Post"},
    {"data": "11/3/2014 - Australian doctors perform pioneering heart transplants - Telegraph, BBC, HuffPost, CNN"},
    {"data": "10/31/2014 - Struggling New York Students Find a Future in Watchmaking - The Wall Street Journal"},
    {"data": "10/30/2014 - Midterm Elections 2014: No TV Cable? Candidates Struggle To Court The Cord-Cutter Vote - IB Times"},
    {"data": "10/29/2014 - Massachusetts town wants to ban tobacco sales - Reuters"},
    {"data": "10/28/2014 - 3 Reasons Why Midterm Elections Are Worth Your Attention - Mashable"},
    {"data": "10/27/2014 - House Panel Questions U.S. Quarantine Procedures - The Wall Street Journal"},
    {"data": "10/24/2014 - Senator Coburn highlights ridiculous government spending in final Wastebook - The Washington Times"},
    {"data": "10/23/2014 - Obama admin. to allow thousands of Haitians into U.S. without visas - The Washington Times"},
    {"data": "10/22/2014 - Colorado officials want ban on most marijuana edibles - New York Daily News"},
    {"data": "10/21/2014 - Canada’s experimental Ebola vaccine - Reuters"},
    {"data": "10/20/2014 - Court Says Parents of Facebook Phony Can Be Liable for Defamation - Atlanta DailyReport.com"},
    {"data": "10/17/2014 - Africa stems Ebola via border closings - Associated Press"},
    {"data": "10/16/2014 - Why Blood Transfusions From Ebola Survivor Dr. Kent Brantly Could Help Patients - ABC News"},
    {"data": "10/15/2014 - Google Glass user treated for internet addiction caused by the device - The Guardian"},
    {"data": "10/14/2014 - Questions remain about how Dallas nurse got Ebola - CNN"},
    {"data": "10/10/2014 - Columbus Day 2014"},
    {"data": "10/9/2014 - 2 Americans, 1 German win Nobel for super-zoom microscopes - Salt Lake Tribune"},
    {"data": "10/8/2014 - Brain Trauma to Affect One in Three Players, NFL Agrees - The New York Times"},
    {"data": "10/7/2014 - Amid Ebola fears, should the U.S. ban air travel from West Africa? - CBS News"},
    {"data": "10/6/2014 - FAA approves drones for moviemaking - USA Today"},
    {"data": "10/3/2014 - License plate scanner networks capture movements - Associated Press"},
    {"data": "10/2/2014 - California becomes first U.S. state to ban plastic grocery bags - Reuters"},
    {"data": "10/1/2014 - US Troops Begin Efforts to Combat Ebola in Africa - The Wall Street Journal"},
    {"data": "9/30/2014 - States Push High School Civics Exam Requirement - US News & World Report"},
    {"data": "9/29/2014 - NJ teen & family join fight to keep “God” in the Pledge of Allegiance - Philly.com and NJ.com"},
    {"data": "9/26/2014 - US-led airstrikes damage ISIS-held oil fields in Syria - New York Post"},
    {"data": "9/25/2014 - Obama Addresses Islamic State Threat in United Nations Speech - The Wall Street Journal"},
    {"data": "9/24/2014 - The 12 governors’ races you need to watch this fall - The Washington Post"},
    {"data": "9/23/2014 - Obama faces busy week at United Nations - USA Today"},
    {"data": "9/22/2014 - Appeals Court won’t reconsider school’s US flag shirt ban - San Jose Mercury News"},
    {"data": "9/19/2014 - Australian authorities foil Islamic State plot for public beheadings - The Sacramento Bee and London's Daily Telegraph"},
    {"data": "9/18/2014 - Citing security threat, Obama expands U.S. role fighting Ebola - Reuters"},
    {"data": "9/17/2014 - Gen John Allen will lead new global coalition to crush Islamic State - London's Daily Telegraph"},
    {"data": "9/16/2014 - NYC High School Dress Code Crackdown - SILive, CS Monitor, ABCNews"},
    {"data": "9/15/2014 - Just 63% Know Which Parties Control the House and Senate - Rasmussen Reports"},
    {"data": "9/12/2014 - Obama to ISIS: ‘If you threaten America, you will find no safe haven’ - NY Post"},
    {"data": "9/11/2014 - 9/11 memorial and museum will open for families of victims, first responders after anniversary ceremony - New York Daily News"},
    {"data": "9/10/2014 - Baltimore gears up to enjoy Star-Spangled Banner’s 200th anniversary - The Patriot-News (Central PA)"},
    {"data": "9/9/2014 - Obama delays action on immigration reform until after November elections - New York Daily News"},
    {"data": "9/8/2014 - Reports of missing Libyan planes raise 9/11 terror fears - USA Today"},
    {"data": "9/5/2014 - Ukraine’s Poroshenko meets Western leaders before NATO summit - The Sydney Morning Herald"},
    {"data": "9/4/2014 - CVS stops selling tobacco, offers quit-smoking programs - USA Today"},
    {"data": "9/3/2014 - Amid ISIS violence, Saudi king warns of threat to U.S. - CBS News"},
    {"data": "9/2/2014 - Emerging solar plants scorch birds in mid-air - Yahoo News"},
    {"data": "8/29/2014 - App Forces Kids To Return Parents’ Calls - Forbes"},
    {"data": "8/28/2014 - Iran ‘will speed arming of Palestinians’ after Israeli drone downed - Yahoo News (Australia)"},
    {"data": "8/27/2014 - Ukraine: Russian tanks have crossed the border - Associated Press"},
    {"data": "8/26/2014 - What kind of risk does ISIS pose to the U.S.? - CBS News"},
    {"data": "8/25/2014 - Liberia police fire on protesters as West Africa’s Ebola toll hits 1,350 - Reuters"},
    {"data": "6/13/2014 - With Baghdad “in jeopardy,” U.S. mulls next move - CBS News"},
    {"data": "6/12/2014 - 57,000 still awaiting initial VA hospital visits, audit shows - CBS News"},
    {"data": "6/11/2014 - U.S. to Provide Lawyers for Children illegally crossing the border from Mexico - New York Times"},
    {"data": "6/10/2014 - Alaska students who didn’t pass exit exam can now get diplomas - Anchorage Daily News"},
    {"data": "6/9/2014 - Seattle approves hike in minimum wage to $15 per hour - Reuters"},
    {"data": "6/6/2014 - D-day veterans find their bonds remain strong after 70 years - The Guardian"},
    {"data": "6/5/2014 - Your electric bill will skyrocket with new energy regulation - Associated Press"},
    {"data": "6/4/2014 - Bowe Bergdahl: Hero or deserter? - CBS News"},
    {"data": "6/3/2014 - Chinese dare recall Tiananmen Square massacre - USA Today"},
    {"data": "6/2/2014 - Scores of undocumented migrants dropped off in Arizona - Arizona Republic"},
    {"data": "5/30/2014 - Google building self-driving cars with no driver seat, steering wheels - Reuters"},
    {"data": "5/29/2014 - Report confirms “significant delays” in Veterans Affairs health care - CBS News"},
    {"data": "5/28/2014 - Redskins fire back against Harry Reid, senators on name change - The Washington Times"},
    {"data": "5/27/2014 - Census: Texas boom times spur fast-growing cities, jobs, housing - Los Angeles Times"},
    {"data": "5/23/2014 - Memorial Day 2014 - USMemorialDay.org"},
    {"data": "5/22/2014 - U.S. Marine jailed in Mexico - Fox News"},
    {"data": "5/21/2014 - U.S. Charges Five in Chinese Army With Hacking - The Wall Street Journal"},
    {"data": "5/20/2014 - Skeptical Scientists Debunk White House Global Warming Report - Daily Caller"},
    {"data": "5/19/2014 - France breaks promise to fly vets over for D-Day anniversary - New York Post"},
    {"data": "5/16/2014 - EU Court Backs “Right to be Forgotten” on Google - BBC News"},
    {"data": "5/15/2014 - Highway Funding Faces Bumpy Road - CBS News"},
    {"data": "5/14/2014 - Driver handcuffed at gunpoint over license plate-reader error - San Francisco Chronicle"},
    {"data": "5/13/2014 - FAA, Drones Clash on Rules for Unmanned Aircraft - The Wall Street Journal"},
    {"data": "5/12/2014 - US advisers reach Nigeria to help look for kidnapped schoolgirls - New York Post"},
    {"data": "5/9/2014 - Tech giants urge rethink of net neutrality changes - BBC News"},
    {"data": "5/8/2014 - Feds approve then revoke approval for powdered alcohol Palcohol - CBS News"},
    {"data": "5/7/2014 - Supreme Court upholds Christian prayers at city council meetings - Los Angeles Times and The Wall Street Journal"},
    {"data": "5/6/2014 - U.S., Philippines begin war games focusing on maritime threats - Reuters"},
    {"data": "5/5/2014 - Kidnapped Nigeria school girls reportedly sold as brides to Islamic Boko Haram militants - CBS News"},
    {"data": "5/2/2014 - SpaceX wants to Replace Russia as NASA’s Space Station Transport - Business Week"},
    {"data": "5/1/2014 - Colo. to revisit edible marijuana rules after deaths - USA Today"},
    {"data": "4/30/2014 - Two U.S. soldiers lose bid to dress according to religious custom - Reuters"},
    {"data": "4/29/2014 - Israel says no to peace talks until Hamas recognizes Israel - London's Daily Telegraph and Bloomberg News"},
    {"data": "4/28/2014 - E-Cig Makers Breathe Easier After FDA Proposes Rules - The Wall Street Journal"},
    {"data": "4/25/2014 - Study: Fuels from corn waste not better than gas - Associated Press"},
    {"data": "4/24/2014 - Supreme Court upholds Michigan’s ban on racial preferences in university admissions - CBS News and The Washington Post"},
    {"data": "4/23/2014 - U.S. Supreme court hears TV broadcasters’ case against Aereo - San Jose Mercury News"},
    {"data": "4/22/2014 - Obama administration delays Keystone XL pipeline decision - The Washington Post"},
    {"data": "4/21/2014 - Smuggled cellphone use a growing concern for U.S. prisons - Reuters"},
    {"data": "4/18/2014 - “Grandparent scam” explained: What you need to know - CBS News"},
    {"data": "4/17/2014 - Casual pot use causes brain abnormalities in young: study - Reuters"},
    {"data": "4/16/2014 - Russia Tests Obama’s Ability To Stop Its Advances - Associated Press"},
    {"data": "4/15/2014 - Amazon is paying unhappy workers to quit - Los Angeles Times"},
    {"data": "4/14/2014 - Ukraine to launch anti-terror operation - Associated Press"},
    {"data": "4/11/2014 - Congress to Iran: Ambassador’s application denied - Associated Press"},
    {"data": "4/10/2014 - Obama Targets Unequal Pay Between Men, Women - The Wall Street Journal"},
    {"data": "4/9/2014 - West Africa Ebola outbreak among ‘most challenging’ ever: WHO - Agence France-Presse"},
    {"data": "4/8/2014 - The U.S. Energy Boom Lifts Low-Income Workers Too - The Wall Street Journal"},
    {"data": "4/7/2014 - Philadelphia Uses ‘The Mosquito’ To Buzz Away Loitering Teens - CBS News Philadelphia"},
    {"data": "4/4/2014 - NATO military chief: Russia could invade Ukraine 12 hours after order - London's Daily Telegraph"},
    {"data": "4/3/2014 - Making Iran captor UN ambassador ‘like spitting on us’ - New York Post"},
    {"data": "4/2/2014 - Vietnam War Hero who blinked “torture” in Morse code dies - CBS News"},
    {"data": "4/1/2014 - Washington mudslide: America’s under-reported tragedy - London's Daily Telegraph"},
    {"data": "3/31/2014 - Connecticut becomes first state to pass $10.10 minimum wage - Reuters"},
    {"data": "3/28/2014 - President Obama gives Medal of Honor to 24 vets from 3 wars - Associated Press"},
    {"data": "3/27/2014 - White House, others decry Saudi move to deny reporter for Israeli paper on Obama trip - CNN"},
    {"data": "3/26/2014 - Nuclear Security Guidelines Adopted by More Than 30 Countries - The Wall Street Journal"},
    {"data": "3/25/2014 - Supreme Court to weigh religious rights of corporations - The Washington Times"},
    {"data": "3/21/2014 - Kansas, Arizona win proof-of-citizenship requirement in voting suit - Los Angeles Times"},
    {"data": "3/20/2014 - Electric customers forced to get smart meters or pay extra monthly charges - Maryland Gazette"},
    {"data": "3/19/2014 - Latest NSA surveillance program exposed - The Washington Post"},
    {"data": "3/18/2014 - Russian Deputy PM Laughs at Obama’s Sanctions - ABC News (ABC15.com)"},
    {"data": "3/17/2014 - U.S. Risks National Blackout From Small-Scale Attack - The Wall Street Journal"},
    {"data": "3/14/2014 - Malaysia Airlines Flight 370 mystery deepens - CBS News"},
    {"data": "3/13/2014 - German Companies Take Back the Power - The Wall Street Journal"},
    {"data": "3/12/2014 - Netanyahu tells West ‘Drop your illusions about Iran’ - Agence France-Presse"},
    {"data": "3/11/2014 - Yik Yak app disabled in Chicago school districts - Chicago Tribune"},
    {"data": "3/10/2014 - Russia sends more troops to disputed Crimea - New York Post"},
    {"data": "3/7/2014 - U.S. Justice Dept. sues Philly school district over beard-length rule - Philly.com"},
    {"data": "3/6/2014 - College-entrance SAT exam set for major overhaul in 2016 - Reuters"},
    {"data": "3/5/2014 - Kerry Warns Russia of Further Steps, Offers Ukraine Aid - The Wall Street Journal"},
    {"data": "3/4/2014 - Obama presses Netanyahu for movement in Mideast peace talks - CBS News"},
    {"data": "3/3/2014 - New ID Policy Aims To Curb Crime At Tennessee State University - News Channel 5 Nashville"},
    {"data": "2/28/2014 - Cellphone led to capture of top drug lord “El Chapo” - CNN"},
    {"data": "2/27/2014 - California farmers to get ‘zero’ federal water - Bloomberg News"},
    {"data": "2/26/2014 - AZ bill letting businesses deny service for religious reasons sparks heated debate - Associated Press"},
    {"data": "2/25/2014 - Budget cuts to slash Army to smallest since before WWII - Reuters"},
    {"data": "2/24/2014 - Ukraine peace deal signed, opens way for new elections - Reuters"},
    {"data": "2/21/2014 - Ukraine protests: 21 killed amid ‘sniper attacks’ as fresh fighting breaks Kiev truce - London's Daily Telegraph"},
    {"data": "2/20/2014 - Union Suffers Big Loss at Tennessee VW Plant - The Wall Street Journal"},
    {"data": "2/19/2014 - German Chancellor Pushes For NSA-Proof European Internet - IB Times"},
    {"data": "2/18/2014 - Snow day’s virtual classroom: lessons at home - NorthJersey.com"},
    {"data": "2/17/2014 - Presidents Day 2014"},
    {"data": "2/14/2014 - Canadian moguls skier Alex Bilodeau dedicates gold to brother - Reuters"},
    {"data": "2/13/2014 - Assault on California Power Station Raises Alarm on Potential for Terrorism - The Wall Street Journal"},
    {"data": "2/12/2014 - Another part of the Affordable Care Act delayed for a year - USA Today"},
    {"data": "2/11/2014 - Lake Superior may freeze over completely for the first time since 1996 - UPI News Agency"},
    {"data": "2/10/2014 - Seventeen solo athletes set to represent their nations at Sochi Games - Canada.com"},
    {"data": "2/7/2014 - Kansas teen uses 3-D printer to make hand for boy - The Kansas City Star"},
    {"data": "2/6/2014 - ‘Obamacare’ will reduce US workforce, report finds - BBC News"},
    {"data": "2/5/2014 - Cars that speak to one another? Tech on the way - Russia's RT.com"},
    {"data": "2/4/2014 - Iraqi army bombards Fallujah in preparation for ground assault - Reuters"},
    {"data": "1/31/2014 - Long Island man, fed up with potholes, does repairs himself - Long Island Newsday"},
    {"data": "1/30/2014 - NSA targeted ‘Angry Birds,’ Google Maps to gather data - New York Post"},
    {"data": "1/29/2014 - Ukraine’s protesters win everything but President’s resignation - Daily Telegraph"},
    {"data": "1/28/2014 - Obama’s ‘s SOTU speech: Questions of emphasis - USA Today"},
    {"data": "1/27/2014 - Marines Delay Female Fitness Plan After Half Fail - USA Today"},
    {"data": "1/24/2014 - British veterans commemorate 70th anniversary of Anzio landings in Italy - London's Daily Telegraph"},
    {"data": "1/23/2014 - Warships part of US contingency plan for Sochi Olympics - ABC News (ABC15.com)"},
    {"data": "1/22/2014 - Propane shortage sends suppliers scrambling, prices jumping - Yahoo Finance"},
    {"data": "1/21/2014 - West, Iran enact nuclear deal - AP, Reuters and Daily Beast"},
    {"data": "1/20/2014 - Dr. Martin Luther King Jr."},
    {"data": "1/17/2014 - What Secrets Your Phone Is Sharing About You - The Wall Street Journal"},
    {"data": "1/16/2014 - Fed judge rules Chicago ban on gun sales unconstitutional - Chicago Sun-Times"},
    {"data": "1/15/2014 - 2014 State of the State Address"},
    {"data": "1/14/2014 - Colorado pot shops likely targets of cartels, say experts - Fox News"},
    {"data": "1/13/2014 - 70 percent of adults report ‘digital eye strain’ - NBC News"},
    {"data": "1/10/2014 - Ants to be sent to the International Space Station - Daily Telegraph"},
    {"data": "1/9/2014 - Florida to Pass New York State’s Population - ABC News"},
    {"data": "1/8/2014 - Americans in the dark about incandescent light bulb ban - NBC News"},
    {"data": "1/7/2014 - US fears over Al-Qaeda takeover of key Iraqi cities - Daily Telegraph"},
    {"data": "1/6/2014 - U.S. breaker to help Russian, Chinese ships stuck in Antarctic ice - Reuters"},
    {"data": "12/20/2013 - Merry Christmas – Back on Jan. 6"},
    {"data": "12/19/2013 - A Race to Preserve the Voices of Holocaust’s Last Survivors - The Wall Street Journal"},
    {"data": "12/18/2013 - Study: Earth was warmer in Roman and Medieval Times - The Daily Caller"},
    {"data": "12/17/2013 - Google buys 8th robotics company in 6 months - The New York Times"},
    {"data": "12/16/2013 - Rare snow blankets Middle East - Chicago Tribune"},
    {"data": "12/13/2013 - Canada to claim North Pole - USA Today"},
    {"data": "12/12/2013 - NYC Board Of Health Mandates Flu Shot For Children - IB Times and CBS NY"},
    {"data": "12/10/2013 - NSA spied on gamers - Associated Press"},
    {"data": "12/9/2013 - Many NFL Players Want Thursday Games To Disappear - CBS News Detroit"},
    {"data": "12/6/2013 - News media protest White House press access limits - Associated Press"},
    {"data": "12/5/2013 - Principal bans students from speaking Spanish in class - Houston's KHOU 11 News"},
    {"data": "12/4/2013 - U.S. Supreme Court takes Hobby Lobby case - NewsOK.com"},
    {"data": "12/3/2013 - Amazon testing delivery by drone - USA Today"},
    {"data": "12/2/2013 - Former hostages react to Iran’s nuclear deal - Denver Post"},
    {"data": "11/22/2013 - Thanksgiving 2013"},
    {"data": "11/21/2013 - Iran’s supreme leader vows no retreat on nuclear ‘rights’ - Australia's News.com.au"},
    {"data": "11/20/2013 - A Russian GPS Using U.S. Soil Stirs Spy Fears - The New York Times"},
    {"data": "11/19/2013 - Supreme Court Declines Challenge to NSA on Verizon Records - ABC News"},
    {"data": "11/18/2013 - Obama’s Green Power Push - YahooNews"},
    {"data": "11/15/2013 - Retired Police Officer Arrested for Sharing Gospel in NJ Mall - NJ.com"},
    {"data": "11/14/2013 - IRS refunded $4 billion to identity thieves last year - CBS News"},
    {"data": "11/13/2013 - Senator: Chicken Slaughtered, Raised In China Could Pose Major Risk - CBS New York, NY Post and NY Daily News"},
    {"data": "11/12/2013 - FDA moves to ban trans fats from processed foods - Daily Telegraph and NY Post"},
    {"data": "11/11/2013 - Veterans Day 2013"},
    {"data": "11/8/2013 - Iran Talks Won’t Change U.S. Missile Plans in Europe, Kerry Says - The Wall Street Journal"},
    {"data": "11/7/2013 - Asian Carp DNA Detected in Lake Michigan Sample - ABC News"},
    {"data": "11/6/2013 - China’s nuclear subs capable of widespread attack on U.S. - The Washington Times"},
    {"data": "11/5/2013 - Drug Smuggling Super Tunnel Found - UK Reuters and Britain's Sky News"},
    {"data": "11/4/2013 - Doctors Resisting ObamaCare - New York Post"},
    {"data": "11/1/2013 - Drive in Google Glass, get a ticket - CNN"},
    {"data": "10/31/2013 - Obama administration knew millions could not keep their health insurance - New York Post"},
    {"data": "10/30/2013 - British man charged with hacking U.S. military networks - Reuters"},
    {"data": "10/29/2013 - Israeli tunnel hit by cyber attack - USA Today"},
    {"data": "10/28/2013 - Duel Erupts on the High Seas - The Wall Street Journal"},
    {"data": "10/25/2013 - Germany summons US envoy amid rage over Merkel spy claims - Agence France-Presse"},
    {"data": "10/24/2013 - How to get and keep a job… - StudentNewsDaily Editorial category"},
    {"data": "10/23/2013 - Obama puts happy face on disastrous Obamacare rollout"},
    {"data": "10/22/2013 - How stores use your phone’s WiFi to track your shopping habits - The Washington Post"},
    {"data": "10/21/2013 - Can students be barred from wearing patriotic clothes? Dispute goes to court. - The Christian Science Monitor and Associated Press"},
    {"data": "10/18/2013 - US-Egypt relations in turmoil: ‘Entire Middle East could suffer’ - New York Post"},
    {"data": "10/17/2013 - U.S. Supreme Court hears case on Michigan Affirmative-action ban - CBS News"},
    {"data": "10/16/2013 - Israel: Easing pressure on Iran would be ‘historic mistake’ - The Chicago Tribune"},
    {"data": "10/15/2013 - U.S. Is Overtaking Russia as Largest Oil-and-Gas Producer - The Wall Street Journal"},
    {"data": "10/14/2013 - Columbus Day 2013"},
    {"data": "10/11/2013 - Man Controls Artificial Leg Using Only His Brain - The Wall Street Journal"},
    {"data": "10/10/2013 - Obamacare website looks “like nobody tested it,” programmer says - CBS News"},
    {"data": "10/9/2013 - Police, schools tap social media to track behavior - NBC News"},
    {"data": "10/8/2013 - A million vets are coming to DC to demand their monuments be opened - The Washington Times"},
    {"data": "10/7/2013 - Healthcare costs - StudentNewsDaily"},
    {"data": "10/4/2013 - Facebook’s Company Town - The Wall Street Journal"},
    {"data": "10/3/2013 - Israel PM Netanyahu: Iran Pres. Rouhani is a ‘wolf in sheep’s clothing’ - NY Post, WSJ and Washington Times"}
]


@app.route('/')
def home_page():
    form = BigDataStoreForm()
    data = []
    return render_template('home.html',
               title='Rest Service',
               form=form,
               searchitems=data)

@app.route('/us/rawdata/1.0/searchitems', methods=['GET', 'POST'])
@requires_auth
def searchitems():
    try:
        if request.method == 'GET':
            data = {'items': BigData}
            return jsonify(data)

        elif request.method == 'POST':
            search_word = request.form['search_word']
            records =  []
            for record in BigData:
                if search_word in record['data']:
                    records.append(record)
            return jsonify(records)
    except:
        return {
            'error': "server unable to handle the request"
        }

@app.route('/us/rawdata/1.0/searchitems/<int:top_limit>', methods=['GET'])
@requires_auth
def search_top_limit_items(top_limit):
    data = BigData[:top_limit]
    data = {'items': data}
    return jsonify(data)